--Desde ORACLE

SELECT ne.FICHA as  EmplID, ne.FECING AS HireDate, ne.FECNAC,ne.FECRET AS TermDate,ne.SEXO AS Gender, 
round((TRUNC(SYSDATE) - to_date(ne.FECNAC)) / 365)  edad,
CASE (SUBSTR(ne.ficha,1,1))
	WHEN 'C' THEN 'CONTRATADO'
	WHEN 'A' THEN 'APRENDIZ'
	ELSE 'FIJO' END TipoPersonal,
	to_char(NVL(SUE.SUEDIA*30,1000),'999999999G00') Sueldo_mensual,
	ne.tnom_tipnom tipoNomina,
	re.id_grupo grupo,
	g.DESGRU,
	NVL(ne.nivedu,9) niveleducativo,
	NVL(ed.DESNIV,'SIN DATOS') nivelEduc,
	NVL(rl.ID_PROFESION,9) idProfesion, NVL(pr.DESPRF,'SIN DATOS') Profesion,
	rl.ID_FINIQUITO, rr.DESDE1

	
FROM INFOCENT.NM_EMPLEADO ne , INFOCENT.NM_RELACION_PAGO re, INFOCENT.NMT023 g, INFOCENT.NMT057 ed,
INFOCENT.TA_RELACION_LABORAL rl, INFOCENT.NMT045 pr, INFOCENT.NMT035 rr,(SELECT s.CIA_CODCIA,s.TRAB_FICTRA , max(s.SUEDIA) SUEDIA from NMM004_RESP s
GROUP BY s.CIA_CODCIA,s.TRAB_FICTRA) sue

--NMM004_RESP SUE
WHERE ne.CIA_CODCIA ='01'
AND ne.FICHA = re.FICHA
AND re.ID_EMPRESA =g.CIA_CODCIA
AND re.ID_NOMINA = g.TNOM_TIPNOM
AND re.ID_GRUPO = g.CODGRU
AND ne.NIVEDU = ed.CODNIV(+) 
AND ne.CIA_CODCIA = rl.ID_EMPRESA
AND ne.FICHA = rl.FICHA
AND rl.ID_PROFESION = pr.CODPRF(+)
AND rl.ID_FINIQUITO = rr.CODDES(+)
AND ne.CIA_CODCIA  = SUE.CIA_CODCIA(+)  
AND ne.FICHA = SUE.TRAB_FICTRA(+)

